# basic options
title: 2nd Assignment Reproducible Research
author: JZstats
email: jzstats@yandex.com
description: This website showcases the project I produced for the 2nd assignment of the 5th Course 'Reproducible Research' from 'Data Science Specialization' by 'Johns Hopkins University' at Coursera.
github_username:  jzstats

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
